apiVersion: apps/v1
kind: Deployment
metadata:
  name: farming-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: farming-app
  template:
    metadata:
      labels:
        app: farming-app
    spec:
      containers:
        - name: farming-app
          image: farming-app
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
