apiVersion: v1
kind: Service
metadata:
  name: farming-app-service
spec:
  type: NodePort
  selector:
    app: farming-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001 # Accessible on port 30001
